"""End-to-End Business Report and Peer Review Generator.

Laboratory 4: End-to-End Business Report and Peer Review

This module ingests a simulated JSON API response, cleans string fields
by removing extra whitespace, extracts specific profile IDs using Regex,
and exports an executive Excel report with structured data for peer review.

Functions:
- `load_json_response(data) -> dict`: Load JSON API response
- `clean_string_fields(record) -> dict`: Remove extra whitespace from strings
- `extract_profile_id(text) -> Optional[str]`: Extract profile ID using Regex
- `process_records(json_data) -> list[dict]`: Clean and extract IDs from records
- `export_to_excel(records, output_file) -> None`: Generate Excel report
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, List, Dict, Optional

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


def load_json_response(data: dict | str) -> dict:
	"""Load JSON API response from dict or JSON string.

	Args:
		data: Dictionary or JSON string containing the API response

	Returns:
		Parsed JSON data as a dictionary

	Raises:
		json.JSONDecodeError: If string is not valid JSON
		TypeError: If data type is not dict or str
	"""
	if isinstance(data, str):
		return json.loads(data)
	elif isinstance(data, dict):
		return data
	else:
		raise TypeError(f"Expected dict or str, got {type(data).__name__}")


def clean_string_fields(record: Dict[str, Any]) -> Dict[str, Any]:
	"""Remove extra whitespace from all string fields in a record.

	Applies strip() to all string values, handling leading/trailing spaces
	and normalizing internal spacing.

	Args:
		record: Dictionary record to clean

	Returns:
		Dictionary with cleaned string fields
	"""
	cleaned = {}
	for key, value in record.items():
		if isinstance(value, str):
			cleaned[key] = value.strip()
		else:
			cleaned[key] = value
	return cleaned


def extract_profile_id(text: str) -> Optional[str]:
	"""Extract profile ID from audit notes using Regex.

	Searches for patterns matching: EXP-XXXXX-X (e.g., EXP-88194-A)

	Args:
		text: Text to search for profile ID

	Returns:
		Extracted profile ID string, or None if not found
	"""
	match = re.search(r"EXP-\d{5}-[A-Z]", text)
	return match.group(0) if match else None


def process_records(json_data: dict) -> List[Dict[str, Any]]:
	"""Process records: clean strings and extract profile IDs.

	Args:
		json_data: Parsed JSON API response

	Returns:
		List of processed records with cleaned fields and extracted IDs

	Raises:
		ValueError: If results key is missing or not a list
	"""
	if "results" not in json_data:
		raise ValueError("JSON data missing 'results' key")

	results = json_data["results"]

	if not isinstance(results, list):
		raise ValueError("'results' key must contain a list")

	processed = []
	for record in results:
		# Clean string fields
		cleaned = clean_string_fields(record)

		# Extract profile ID from audit_notes
		profile_id = extract_profile_id(cleaned.get("audit_notes", ""))

		# Add processed record with extracted ID
		processed_record = {
			"profile_id": profile_id,
			"cleaned_name": cleaned.get("raw_name", ""),
			"credit_score": cleaned.get("credit_score"),
			"audit_notes": cleaned.get("audit_notes", ""),
		}
		processed.append(processed_record)

	return processed


def export_to_excel(
	records: List[Dict[str, Any]],
	output_file: str,
	report_metadata: Optional[Dict[str, str]] = None,
) -> None:
	"""Export processed records to Excel with executive formatting.

	Creates a professional Excel report with headers, styling, and validation.

	Args:
		records: List of processed record dictionaries
		output_file: Path to output Excel file
		report_metadata: Optional metadata (generated_by, status) for header

	Raises:
		ValueError: If no records to export
		IOError: If unable to write file
	"""
	if not records:
		raise ValueError("No records to export")

	output_path = Path(output_file)
	output_path.parent.mkdir(parents=True, exist_ok=True)

	# Create workbook
	wb = openpyxl.Workbook()
	ws = wb.active
	ws.title = "Executive Report"

	# Define styles
	header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
	header_font = Font(bold=True, color="FFFFFF", size=12)
	center_alignment = Alignment(horizontal="center", vertical="center")
	wrap_alignment = Alignment(horizontal="left", vertical="top", wrap_text=True)
	border = Border(
		left=Side(style="thin"),
		right=Side(style="thin"),
		top=Side(style="thin"),
		bottom=Side(style="thin"),
	)

	# Add metadata header if provided
	row = 1
	if report_metadata:
		ws[f"A{row}"] = f"Generated By: {report_metadata.get('generated_by', 'N/A')}"
		ws[f"A{row}"].font = Font(italic=True, size=10)
		row += 1

		ws[f"A{row}"] = f"Status: {report_metadata.get('status', 'N/A')}"
		ws[f"A{row}"].font = Font(italic=True, size=10)
		row += 2

	# Write headers
	headers = ["Profile ID", "Cleaned Name", "Credit Score", "Audit Notes"]
	for col_num, header in enumerate(headers, 1):
		cell = ws.cell(row=row, column=col_num)
		cell.value = header
		cell.fill = header_fill
		cell.font = header_font
		cell.alignment = center_alignment
		cell.border = border

	row += 1

	# Write data rows
	for record in records:
		ws.cell(row=row, column=1).value = record["profile_id"]
		ws.cell(row=row, column=2).value = record["cleaned_name"]
		ws.cell(row=row, column=3).value = record["credit_score"]
		ws.cell(row=row, column=4).value = record["audit_notes"]

		# Apply formatting to data rows
		for col_num in range(1, 5):
			cell = ws.cell(row=row, column=col_num)
			cell.border = border
			if col_num in [1, 3]:  # Profile ID and Credit Score
				cell.alignment = center_alignment
			else:
				cell.alignment = wrap_alignment

		row += 1

	# Adjust column widths
	ws.column_dimensions["A"].width = 15
	ws.column_dimensions["B"].width = 25
	ws.column_dimensions["C"].width = 15
	ws.column_dimensions["D"].width = 50

	# Save workbook
	wb.save(str(output_path))
	print(f"Successfully exported {len(records)} records to {output_file}")


def generate_business_report(
	json_data: dict | str, output_file: str = "executive_report.xlsx"
) -> None:
	"""Main orchestration function for end-to-end report generation.

	Args:
		json_data: JSON API response (dict or string)
		output_file: Path to output Excel file

	Raises:
		ValueError: If data is invalid or processing fails
	"""
	try:
		print("Loading JSON API response...")
		api_response = load_json_response(json_data)

		print("Processing records: cleaning strings and extracting IDs...")
		processed_records = process_records(api_response)
		print(f"Processed {len(processed_records)} records")

		# Extract metadata for report
		metadata = {
			"generated_by": api_response.get("report_generated_by", "N/A"),
			"status": api_response.get("status", "N/A"),
		}

		print(f"Exporting to Excel: {output_file}")
		export_to_excel(processed_records, output_file, report_metadata=metadata)
		print("Report generation complete!")

	except json.JSONDecodeError as e:
		print(f"Error: Invalid JSON format - {e}")
		raise
	except ValueError as e:
		print(f"Error: {e}")
		raise
	except IOError as e:
		print(f"Error: Unable to write file - {e}")
		raise


if __name__ == "__main__":
	# Sample JSON API response
	sample_response = {
		"report_generated_by": "  SYSTEM_ADMIN_USER  ",
		"status": " SUCCESS_COMPLETED ",
		"results": [
			{
				"raw_name": "  alice   smith  ",
				"credit_score": 742,
				"audit_notes": "Approved under profile reference: EXP-88194-A. Verification completed on 2026-07-10.",
			},
			{
				"raw_name": "BOB   JONES  ",
				"credit_score": 612,
				"audit_notes": "Referral triggered. Flagged profile is EXP-33091-B. Manual review required.",
			},
			{
				"raw_name": "  charlie brown ",
				"credit_score": 810,
				"audit_notes": "Excellent history found in system file EXP-11024-C.",
			},
		],
	}

	# Generate the business report
	generate_business_report(sample_response, output_file="executive_report.xlsx")
